### ISSUE TITLE
Real-time requirement of different services

### ISSUE THREAD

**Issue by marenz2569** [dump-dvb/data-accumulator#4]
Currently we write each telegram first to the database and then to gRPC sequentially. See here:
https://github.com/dump-dvb/data-accumulator/blob/9bcb76a660332325666fb4516934d4537629b436/src/processor/mod.rs#L51

This causes problems with different time requirements for both services.
The gRPC should be more or less real-time. The influxdb storage can be a bit delayed, as it is only used for saving historic data and doing analytics on them.

Suggested solution: Handle the gRPC and influxdb write in two independent threads.

**Comment by tanneberger** [comment]
solved done. We have now two different channels
